### PR TITLE
added hackingwithswift as a useful resource

### PR DESCRIPTION
**Pull request by craigdennis**

### CODE REVIEW

**Comment by craigdennis** [comment]
adding resource hackingwithswift

**Comment by BohdanOrlov** [comment]
Thanks for the contribution but you edited the wrong file which is autogenerated. Please edit only ’Content.yml’

**Comment by craigdennis** [comment]
Hey there. Sorry about that. New to github so getting the hang of it.

**Comment by BohdanOrlov** [comment]
@craigdennis no problem, if you have difficulties read [the contribution guide](https://github.com/BohdanOrlov/iOS-Developer-Roadmap/blob/master/HowTo/HOWTOPR.md) and resubmit if you want

**Pull request closed without merging**
